-- Migracao 6: catalogo de servicos padronizados + etapas automaticas
-- Rode no SQL Editor do Supabase, depois de ja ter rodado migration_05_edit_any_profile.sql

create table service_templates (
  code text primary key,
  name text not null,
  parent_code text references service_templates(code) on delete cascade,
  position int not null default 0
);

alter table service_templates enable row level security;
create policy "authenticated read service_templates" on service_templates for select using (auth.uid() is not null);

insert into service_templates (code, name, parent_code, position) values
  ('81', 'Abertura de Matrículas', null, 1),
  ('4', 'Aferiçao de Obra na Receita Federal', null, 2),
  ('27', 'Alteraçao de Zoneamento', null, 3),
  ('28', 'Análise de Risco', null, 4),
  ('34', 'Anuência DEER/ECO101', null, 5),
  ('32', 'Anuência Prefeitura', null, 6),
  ('33', 'Anuência SPU', null, 7),
  ('11', 'Aprovaçao de Loteamento', null, 8),
  ('80', 'Aprovaçao de Projeto', null, 9),
  ('69', 'Atualizaçao Cadastral CESAN', null, 10),
  ('70', 'Atualizaçao Cadastral Condominial', null, 11),
  ('68', 'Atualizaçao Cadastral EDP', null, 12),
  ('71', 'Atualizaçao Cadastral SPU', null, 13),
  ('39', 'Averbaçao em Cartório', null, 14),
  ('52', 'Averbaçao Patrimônio de Afetaçao', null, 15),
  ('35', 'Baixa de Gravame', null, 16),
  ('31', 'Cancelamento de Cadastro', null, 17),
  ('64', 'Certidao', null, 18),
  ('25', 'Contrato Particular de Compra e Venda', null, 19),
  ('26', 'Contrato Particular de Doaçao', null, 20),
  ('16', 'Criaçao/Atualizaçao Cadastro Produtor', null, 21),
  ('15', 'Criaçao/Atualizaçao CAR', null, 22),
  ('13', 'Criaçao/Atualizaçao CCIR', null, 23),
  ('14', 'Criaçao/Atualizaçao CIB', null, 24),
  ('20', 'Criaçao/Atualizaçao IPTU', null, 25),
  ('45', 'Declaraçao de ITR', null, 26),
  ('30', 'Descaracterizaçao de Imóvel', null, 27),
  ('3', 'Desdobro', null, 28),
  ('10', 'Desmembramento - Urbano', null, 29),
  ('10.1', 'Planejamento de Campo', '10', 1),
  ('10.2', 'Levantamento em Campo', '10', 2),
  ('10.3', 'Elaboração de peças tecnicas topograficas', '10', 3),
  ('10.4', 'Elaboração de peças tecnicas administrativas', '10', 4),
  ('10.5', 'Protocolo Prefeitura', '10', 5),
  ('10.6', 'Protocolo em Cartório', '10', 6),
  ('77', 'Doaçao', null, 30),
  ('44', 'Emolumento Averbaçao (previsao)', null, 31),
  ('40', 'Emolumento Certidao (previsao)', null, 32),
  ('43', 'Emolumento Registro (previsao)', null, 33),
  ('1', 'Escrituraçao', null, 34),
  ('22', 'Estremaçao', null, 35),
  ('7', 'Fraçao Ideal', null, 36),
  ('17', 'Georreferenciamento', null, 37),
  ('17.1', 'Planejamento de Campo', '17', 1),
  ('17.2', 'Levantamento em Campo', '17', 2),
  ('17.3', 'Elaboração de peças tecnicas topograficas', '17', 3),
  ('17.4', 'Elaboração de peças tecnicas administrativas', '17', 4),
  ('17.5', 'Coleta de assinatura dos confrontantes', '17', 5),
  ('17.6', 'Protocolo em Cartório', '17', 6),
  ('17.7', 'Atualização Cadastral (CCIR, CIB e CAR)', '17', 7),
  ('50', 'Imposto - ITBI', null, 38),
  ('51', 'Imposto - ITCMD', null, 39),
  ('18', 'Incorporaçao', null, 40),
  ('6', 'Instituiçao de Condomínio', null, 41),
  ('6.1', 'Elaboração de Fração Ideal', '6', 1),
  ('6.2', 'Emissão de certidões', '6', 2),
  ('6.3', 'Elaboração de Requerimento', '6', 3),
  ('6.4', 'Registro em Cartório', '6', 4),
  ('19', 'Integralizaçao de Capital Social', null, 42),
  ('23', 'Inventário Extrajudicial', null, 43),
  ('23.1', 'Recebimento de documentos', '23', 1),
  ('23.2', 'Definição do inventariante', '23', 2),
  ('23.3', 'Levantamento dos Bens', '23', 3),
  ('23.4', 'Elaboração da Partilha (Minuta)', '23', 4),
  ('23.5', 'Avaliação dos Bens', '23', 5),
  ('23.6', 'Emissão de certificado notarizado', '23', 6),
  ('23.7', 'Escritura pública de inventário', '23', 7),
  ('23.8', 'Registro da partilha', '23', 8),
  ('23.9', 'Atualização Cadastral', '23', 9),
  ('42', 'Laudo Técnico IDAF', null, 44),
  ('37', 'Levantamento Topográfico', null, 45),
  ('49', 'PCA - Plano de Controle Ambiental', null, 46),
  ('21', 'Pedido de Licença Ambiental', null, 47),
  ('12', 'Pedido de Outorga Onerosa', null, 48),
  ('8', 'Processo Administrativo na Prefeitura', null, 49),
  ('48', 'Projeto Arquitetônico', null, 50),
  ('58', 'Protocolo', null, 51),
  ('83', 'Publicidade e Propaganda', null, 52),
  ('2', 'Registro de Escritura', null, 53),
  ('47', 'Registro de Loteamento', null, 54),
  ('29', 'Regularizaçao de Obra', null, 55),
  ('29.1', 'Regularizaçao de Obra perante prefeitura', '29', 1),
  ('29.2', 'Regularizaçao de Obra perante RF', '29', 2),
  ('29.3', 'Regularizaçao de Obra perante cartório', '29', 3),
  ('24', 'Retificaçao de Área', null, 56),
  ('63', 'Seminário', null, 57),
  ('5', 'Solicitaçao de Habite-se', null, 58),
  ('78', 'Solicitaçao de ITBI', null, 59),
  ('36', 'Solicitaçao de viabilidade concessionárias', null, 60),
  ('41', 'Taxa INSS de Obra (previsao)', null, 61),
  ('46', 'Taxas (previsao)', null, 62),
  ('38', 'Unificaçao de Matrículas', null, 63),
  ('9', 'Usucapiao Extrajudicial', null, 64),
  ('9.1', 'Recebimento de documentos', '9', 1),
  ('9.2', 'Pesquisa de dados', '9', 2),
  ('9.3', 'Levantamento em Campo', '9', 3),
  ('9.4', 'Elaboração de peças tecnicas topograficas', '9', 4),
  ('9.5', 'Elaboração de peças tecnicas administrativas', '9', 5),
  ('9.6', 'Coleta de assinatura dos confrontantes/testemunhas', '9', 6),
  ('9.7', 'Elaboração de Petição', '9', 7),
  ('9.8', 'Emissão de Certidões', '9', 8),
  ('9.9', 'Protocolo escritura Ata Notarial', '9', 9),
  ('9.10', 'Protocolo Registro', '9', 10),
  ('9.11', 'Publicação em Edital', '9', 11),
  ('9.12', 'Análise para Registro', '9', 12),
  ('9.13', 'Certificação do GEO (APENAS se for rural)', '9', 13),
  ('9.14', 'Atualização cadastral', '9', 14);
